package com.javen.dao;

import com.javen.model.Fingerprint;
import com.javen.model.FingerprintKey;

public interface FingerprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fingerprint
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int deleteByPrimaryKey(FingerprintKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fingerprint
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int insert(Fingerprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fingerprint
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int insertSelective(Fingerprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fingerprint
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    Fingerprint selectByPrimaryKey(FingerprintKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fingerprint
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int updateByPrimaryKeySelective(Fingerprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fingerprint
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int updateByPrimaryKey(Fingerprint record);
}