package com.javen.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.javen.model.Archive;
import com.javen.model.Record;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    Record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int updateByPrimaryKey(Record record);
    
    int count(@Param("comid") int comid);
    int countdid(@Param("comid") int comid,@Param("empid") int empid);
    int countwill(@Param("comid") int comid,@Param("will") String will);
    List<Record> findAllPage(@Param("before") int before,@Param("comid") int comid);
    List<Record> findAllPagewill(@Param("before") int before,@Param("comid") int comid,@Param("will") String will);
    List<Record> findAllPagedid(@Param("before") int before,@Param("comid") int comid,@Param("empid") int empid);
    Record findRecord(@Param("comid") int comid,@Param("recordid") int recordId);
    int maxid();
}