package com.javen.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.javen.model.Seal;
import com.javen.model.SealKey;
import com.javen.model.User;

public interface SealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seal
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int deleteByPrimaryKey(SealKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seal
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int insert(Seal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seal
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int insertSelective(Seal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seal
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    Seal selectByPrimaryKey(SealKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seal
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int updateByPrimaryKeySelective(Seal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seal
     *
     * @mbggenerated Sun Jul 22 11:59:21 CST 2018
     */
    int updateByPrimaryKey(Seal record);
    int count(@Param("comid") int comid);
    List<Seal> findAllPage(@Param("before") int before,@Param("comid") int comid);
    Seal findseal(@Param("comid") int comid,@Param("sealid") int sealid);
}