package com.javen.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.javen.model.User;
import com.javen.model.UserKey;


public interface UserMapper extends BaseMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 17 12:40:11 CST 2018
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 17 12:40:11 CST 2018
     */
    Integer insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 17 12:40:11 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 17 12:40:11 CST 2018
     */
    User selectByPrimaryKey(UserKey key);
    
    User selectByTel(@Param("tel")String tel,@Param("password")String password);
    User selectTel(@Param("tel")String tel);
    User isreapt(@Param("empid")int empid,@Param("comid")int comid);
//    User findUser(@Param("comid")int comid,@Param("empid")int empid);
    List<User> findAllPage(@Param("before") int before,@Param("comid") int comid);
    User getname(@Param("empid")int empid,@Param("comid")int comid);
    int count(@Param("comid") int comid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 17 12:40:11 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 17 12:40:11 CST 2018
     */
    int updateByPrimaryKey(User record);
}