package com.javen.model;

import java.util.Date;

public class Archive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.archive_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer archiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.from_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.did_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer didId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.time
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.result
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.image
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.imge_times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer imgeTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer sealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column archive.imge_nums
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer imgeNums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.archive_id
     *
     * @return the value of archive.archive_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getArchiveId() {
        return archiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.archive_id
     *
     * @param archiveId the value for archive.archive_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setArchiveId(Integer archiveId) {
        this.archiveId = archiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.company_id
     *
     * @return the value of archive.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.company_id
     *
     * @param companyId the value for archive.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.from_id
     *
     * @return the value of archive.from_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.from_id
     *
     * @param fromId the value for archive.from_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.did_id
     *
     * @return the value of archive.did_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getDidId() {
        return didId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.did_id
     *
     * @param didId the value for archive.did_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setDidId(Integer didId) {
        this.didId = didId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.time
     *
     * @return the value of archive.time
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.time
     *
     * @param time the value for archive.time
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.result
     *
     * @return the value of archive.result
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.result
     *
     * @param result the value for archive.result
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.image
     *
     * @return the value of archive.image
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.image
     *
     * @param image the value for archive.image
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.times
     *
     * @return the value of archive.times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.times
     *
     * @param times the value for archive.times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.imge_times
     *
     * @return the value of archive.imge_times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getImgeTimes() {
        return imgeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.imge_times
     *
     * @param imgeTimes the value for archive.imge_times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImgeTimes(Integer imgeTimes) {
        this.imgeTimes = imgeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.sealid
     *
     * @return the value of archive.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getSealid() {
        return sealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.sealid
     *
     * @param sealid the value for archive.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setSealid(Integer sealid) {
        this.sealid = sealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column archive.imge_nums
     *
     * @return the value of archive.imge_nums
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getImgeNums() {
        return imgeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column archive.imge_nums
     *
     * @param imgeNums the value for archive.imge_nums
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImgeNums(Integer imgeNums) {
        this.imgeNums = imgeNums;
    }
}