package com.javen.model;

public class Fingerprint extends FingerprintKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.finger
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String finger;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.finger
     *
     * @return the value of fingerprint.finger
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getFinger() {
        return finger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.finger
     *
     * @param finger the value for fingerprint.finger
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setFinger(String finger) {
        this.finger = finger == null ? null : finger.trim();
    }
}