package com.javen.model;

public class FingerprintKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fingerprint.employee_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.company_id
     *
     * @return the value of fingerprint.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.company_id
     *
     * @param companyId the value for fingerprint.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fingerprint.employee_id
     *
     * @return the value of fingerprint.employee_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fingerprint.employee_id
     *
     * @param employeeId the value for fingerprint.employee_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
}