package com.javen.model;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.from_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.did_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer didId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.status
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.reason
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.images_url
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String imagesUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.imge_times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer imgeTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer sealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.imge_nums
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer imgeNums;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.from_id
     *
     * @return the value of record.from_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.from_id
     *
     * @param fromId the value for record.from_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.did_id
     *
     * @return the value of record.did_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getDidId() {
        return didId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.did_id
     *
     * @param didId the value for record.did_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setDidId(Integer didId) {
        this.didId = didId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.company_id
     *
     * @return the value of record.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.company_id
     *
     * @param companyId the value for record.company_id
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time
     *
     * @return the value of record.time
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time
     *
     * @param time the value for record.time
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.status
     *
     * @return the value of record.status
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.status
     *
     * @param status the value for record.status
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.reason
     *
     * @return the value of record.reason
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.reason
     *
     * @param reason the value for record.reason
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.images_url
     *
     * @return the value of record.images_url
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getImagesUrl() {
        return imagesUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.images_url
     *
     * @param imagesUrl the value for record.images_url
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImagesUrl(String imagesUrl) {
        this.imagesUrl = imagesUrl == null ? null : imagesUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.times
     *
     * @return the value of record.times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.times
     *
     * @param times the value for record.times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.imge_times
     *
     * @return the value of record.imge_times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getImgeTimes() {
        return imgeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.imge_times
     *
     * @param imgeTimes the value for record.imge_times
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImgeTimes(Integer imgeTimes) {
        this.imgeTimes = imgeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.sealid
     *
     * @return the value of record.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getSealid() {
        return sealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.sealid
     *
     * @param sealid the value for record.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setSealid(Integer sealid) {
        this.sealid = sealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.imge_nums
     *
     * @return the value of record.imge_nums
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getImgeNums() {
        return imgeNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.imge_nums
     *
     * @param imgeNums the value for record.imge_nums
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImgeNums(Integer imgeNums) {
        this.imgeNums = imgeNums;
    }
}