package com.javen.model;

public class Seal extends SealKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seal.sealname
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String sealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seal.image
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seal.empid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer empid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seal.desc
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seal.sealname
     *
     * @return the value of seal.sealname
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getSealname() {
        return sealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seal.sealname
     *
     * @param sealname the value for seal.sealname
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setSealname(String sealname) {
        this.sealname = sealname == null ? null : sealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seal.image
     *
     * @return the value of seal.image
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seal.image
     *
     * @param image the value for seal.image
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seal.empid
     *
     * @return the value of seal.empid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getEmpid() {
        return empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seal.empid
     *
     * @param empid the value for seal.empid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seal.desc
     *
     * @return the value of seal.desc
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seal.desc
     *
     * @param desc the value for seal.desc
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}