package com.javen.model;

public class SealKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seal.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer sealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seal.comid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    private Integer comid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seal.sealid
     *
     * @return the value of seal.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getSealid() {
        return sealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seal.sealid
     *
     * @param sealid the value for seal.sealid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setSealid(Integer sealid) {
        this.sealid = sealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seal.comid
     *
     * @return the value of seal.comid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public Integer getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seal.comid
     *
     * @param comid the value for seal.comid
     *
     * @mbggenerated Wed Jul 25 20:10:44 CST 2018
     */
    public void setComid(Integer comid) {
        this.comid = comid;
    }
}